name: Python Code Analysis

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze Python Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Ollama service
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        ollama serve &
        sleep 10  # Give Ollama some time to start
        ollama pull llama2

    - name: Run code analysis
      run: python -m src.action
      env:
        OLLAMA_MODEL: llama2
        OLLAMA_HOST: http://localhost:11434
